"""Export the LightGBM shot-value model to a Luau module for the Roblox game.

Roblox can't run ONNX, but the model is a small tree ensemble, so it is written out as Luau tables
plus a tree walker. The generated module is required by the Roblox server and returns the same
probabilities as LightGBM (checked in tests/test_export_luau.py and in the Luau test suite).

    python -m dink_ml.export_luau models/shot_value.lgb.txt --out ../roblox/src/shared/ShotModel.luau
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import lightgbm as lgb
import numpy as np

from .features import FEATURE_VERSION, N_FEATURES


def flatten(booster: lgb.Booster) -> list[dict]:
    """Each tree becomes parallel arrays. Children > 0 are internal node numbers (1-based);
    children <= 0 point at leaf -child (0-based) in `v`."""
    trees = []
    for info in booster.dump_model()["tree_info"]:
        f: list[int] = []; t: list[float] = []; left: list[int] = []; right: list[int] = []; v: list[float] = []

        def visit(node: dict) -> int:
            if "leaf_value" in node:
                v.append(float(node["leaf_value"]))
                return -(len(v) - 1)
            if node.get("decision_type", "<=") != "<=":
                raise ValueError("only numeric <= splits are supported")
            idx = len(f)
            f.append(int(node["split_feature"]) + 1); t.append(float(node["threshold"])); left.append(0); right.append(0)
            left[idx] = visit(node["left_child"])
            right[idx] = visit(node["right_child"])
            return idx + 1

        root = visit(info["tree_structure"])
        trees.append({"f": f, "t": t, "l": left, "r": right, "v": v, "root": root})
    return trees


def predict_flat(trees: list[dict], X: np.ndarray) -> np.ndarray:
    """Reference implementation of the Luau walker, used to verify the export."""
    out = np.zeros(len(X))
    for i, x in enumerate(X):
        s = 0.0
        for tr in trees:
            n = tr["root"]
            while n > 0:
                n = tr["l"][n - 1] if x[tr["f"][n - 1] - 1] <= tr["t"][n - 1] else tr["r"][n - 1]
            s += tr["v"][-n]
        out[i] = s
    return 1.0 / (1.0 + np.exp(-out))


def _nums(xs, fmt="{:.9g}") -> str:
    return ",".join(fmt.format(x) for x in xs)


def to_luau(trees: list[dict], card: dict | None = None) -> str:
    card = card or {}
    info = {k: card[k] for k in ("rows", "auc", "trees", "created", "source") if k in card}
    info_lua = ", ".join(f"{k} = {json.dumps(v)}" for k, v in info.items())
    lines = [
        "--!nocheck",
        "-- Generated by ml/dink_ml/export_luau.py from the trained shot-value model. Do not edit by hand.",
        "-- Input: 21 features in the dink-features-v1 order (see docs/model-contract.md).",
        "local M = {}",
        f'M.featureVersion = "{FEATURE_VERSION}"',
        f"M.nFeatures = {N_FEATURES}",
        f"M.info = {{ {info_lua} }}",
        "local TREES = {",
    ]
    for tr in trees:
        lines.append(f"\t{{root={tr['root']},f={{{_nums(tr['f'], '{}')}}},t={{{_nums(tr['t'])}}},l={{{_nums(tr['l'], '{}')}}},r={{{_nums(tr['r'], '{}')}}},v={{{_nums(tr['v'])}}}}},")
    lines += [
        "}",
        "",
        "-- Probability that the hitting team wins the rally.",
        "function M.predict(x)",
        "\tlocal s = 0",
        "\tfor _, tr in TREES do",
        "\t\tlocal n, f, t, l, r = tr.root, tr.f, tr.t, tr.l, tr.r",
        "\t\twhile n > 0 do",
        "\t\t\tif x[f[n]] <= t[n] then n = l[n] else n = r[n] end",
        "\t\tend",
        "\t\ts += tr.v[1 - n]",
        "\tend",
        "\treturn 1 / (1 + math.exp(-s))",
        "end",
        "",
        "return M",
        "",
    ]
    return "\n".join(lines)


def fixture_luau(trees: list[dict], X: np.ndarray) -> str:
    p = predict_flat(trees, X)
    rows = [f"\t{{ x = {{{_nums(x)}}}, p = {pi:.12g} }}," for x, pi in zip(X, p)]
    return "-- Generated test fixture: feature rows and expected model output.\nreturn {\n" + "\n".join(rows) + "\n}\n"


def _lua(v) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return f"{v:.12g}"
    if isinstance(v, str):
        return json.dumps(v)
    if isinstance(v, list):
        return "{" + ", ".join(_lua(x) for x in v) + "}"
    if isinstance(v, dict):
        return "{" + ", ".join(f"{k} = {_lua(x)}" for k, x in v.items()) + "}"
    raise TypeError(type(v))


def parity_fixture_luau(fixture_json: str | Path) -> str:
    """Convert the TypeScript feature-parity fixture to Luau (1-based player slots), so the Roblox
    port of the rule engine and feature code is checked against the same cases as Python."""
    data = json.loads(Path(fixture_json).read_text())
    cases = []
    for c in data["cases"]:
        st = dict(c["state"])
        st["hitter"] = st["hitter"] + 1
        cases.append({"state": st, "type": c["type"], "target": c["target"], "features": c["features"]})
    body = ",\n".join("\t" + _lua(c) for c in cases)
    return ("-- Generated from ml/tests/fixtures/feature_parity.json by ml/dink_ml/export_luau.py --parity.\n"
            f"return {{ version = {json.dumps(data['feature_version'])}, cases = {{\n{body},\n}} }}\n")


def export(booster: lgb.Booster, out: str | Path, card: dict | None = None, fixture_X: np.ndarray | None = None,
           fixture_out: str | Path | None = None) -> float:
    trees = flatten(booster)
    Path(out).parent.mkdir(parents=True, exist_ok=True)
    Path(out).write_text(to_luau(trees, card))
    if fixture_X is not None and fixture_out:
        Path(fixture_out).parent.mkdir(parents=True, exist_ok=True)
        Path(fixture_out).write_text(fixture_luau(trees, fixture_X))
    X = fixture_X if fixture_X is not None else np.random.default_rng(0).normal(size=(50, N_FEATURES))
    return float(np.max(np.abs(predict_flat(trees, X) - booster.predict(X))))


def main(argv: list[str] | None = None) -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("model", nargs="?", help="LightGBM text model (saved by dink_ml.train)")
    ap.add_argument("--out", default="../roblox/src/shared/ShotModel.luau")
    ap.add_argument("--card", default=None, help="model_card.json to copy metadata from")
    ap.add_argument("--parity", nargs=2, metavar=("FIXTURE_JSON", "OUT_LUAU"),
                    help="also convert the feature-parity fixture for the Luau tests")
    a = ap.parse_args(argv)
    if a.parity:
        Path(a.parity[1]).write_text(parity_fixture_luau(a.parity[0]))
        print(f"wrote {a.parity[1]}")
    if not a.model:
        return
    booster = lgb.Booster(model_file=a.model)
    card = json.loads(Path(a.card).read_text()) if a.card else None
    diff = export(booster, a.out, card)
    print(f"wrote {a.out} · max |Luau - LightGBM| = {diff:.2e}")


if __name__ == "__main__":
    main()
